<?php
	require_once('db_fns.php');
	require_once('article.php');
	require_once('user_auth_fns.php');
	require_once('output_framework_fns.php');
	require_once('output_form_fns.php');
	require_once('output_search_result_fns.php');
	require_once('output_article_fns.php');
	require_once('data_valid_fns.php');
	require_once('ps_pagination.php');
?>
